baseURL: "https://adahafizh.github.io/"
title: ADAHafizh
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 2 
        - name: About
          url: https://adahafizh.github.io/
          weight: 1

params:
    description: "This website hosts Ahmad Dahlan Hafizh's designs, works, and interests."
    author: Ahmad Dahlan Hafizh
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ahmad Dahlan "Hafizh"
          subtitle: "Hey, I'm Hafizh from Jakarta, Indonesia. Senior at New York University Abu Dhabi studying Interactive Media and Computer Science minor. Prospective video game level designer. Passionate in mixed reality, advocating data justice through geospatial visualization, and connecting culture through narrative digital/traditional art exhibitions. Worked with several professors on relevant fields. Former World of Warcraft 6th global best tanking role, raider for 3 years in a static team. Addicted to cooking, dragonboating, bruising while climbing walls, and breakbeat music."
          imageUrl: "pfp.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Projects
              url: projects/
            - name: Experience
              url: experience/
            - name: Looking for DAAH?
              url: https://adahafizh.github.io/daah/
            - name: Archive
              url: archive/

    socialIcons:
        - name: CV
          url: ADAHafizh_CV_2025.pdf
        - name: Email
          url: mailto:adh10023@nyu.edu
        - name: GitHub
          url: https://github.com/ADAHafizh
        - name: YouTube
          url: https://www.youtube.com/@sisipah
        - name: Zoom
          url: https://nyu.zoom.us/launch/chat?src=direct_chat_link&email=adh10023@nyu.edu

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ahmad Dahlan Hafizh"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:  
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2