baseURL: "https://adahafizh.github.io/"
title: ADAHafizh
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This website hosts Ahmad Dahlan Hafizh's designs, works, and interests."
    author: Ahmad Dahlan Hafizh
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ahmad Dahlan "Hafizh"
          subtitle: "Hey, I'm Hafizh from Jakarta, Indonesia. Senior at New York University Abu Dhabi studying Interactive Media and Computer Science minor. Prospective video game level designer. Passionate in mixed reality, advocating data justice through geospatial visualization, and connecting culture through narrative digital/traditional art exhibitions. Worked with several professors on those fields. Former World of Warcraft 6th global best tanking role, raider for 3 years in a static team. Addicted to cooking, dragonboating, bruising while climbing walls, and breakbeat music."
          imageUrl: "pfp.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About
              url: about/
            - name: Courses
              url: courses/
            - name: Projects
              url: projects/
            - name: Looking for DAAH?
              url: https://adahafizh.github.io/daah/
            - name: Archive
              url: archive/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:adh10023@nyu.edu
        - name: Zoom
          url: https://nyu.zoom.us/launch/chat?src=direct_chat_link&email=adh10023@nyu.edu
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Substack
          url: https://pmichaillat.substack.com
        - name: YouTube
          url: https://www.youtube.com/@pmichaillat
        - name: Twitter
          url: https://x.com/pmichaillat
        - name: Bluesky
          url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ahmad Dahlan Hafizh"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2